<a href="https://colab.research.google.com/github/NishaAnjalin/CSH4123-P/blob/main/18sep(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#9)Create 1D array and insert values from 0 to 20 within 3 gap spacve and find the values which are divided by 2.
    #and replace 0 in array which are not satisfied the condition

  #9)Create 1D array and insert values from 0 to 20 within 3 gap spacve and find the values which are divided by 2.
    #and replace 0 in array which are not satisfied the condition

import numpy as np

# Create a 1D array with values from 0 to 20 with a gap of 3
arr = np.arange(0, 21, 3)

# Find the values which are divided by 2
divisible_by_3 = arr % 3 == 0

# Replace values not divisible by 2 with 0
arr[~divisible_by_3] = 0

print(arr)

[ 0  3  6  9 12 15 18]


In [5]:
#10)Create 1D array as data=[1,2,3,4,5,6] and reshaping it as a 2*3 matrix 3*2 matrix

import numpy as np

# Create the 1D array
data = np.array([1, 2, 3, 4, 5, 6])

# Reshape as a 2*3 matrix
matrix_2x3 = data.reshape(2, 3)
print("2x3 matrix:")
print(matrix_2x3)

# Reshape as a 3*2 matrix
matrix_3x2 = data.reshape(3, 2)
print("\n3x2 matrix:")
print(matrix_3x2)

2x3 matrix:
[[1 2 3]
 [4 5 6]]

3x2 matrix:
[[1 2]
 [3 4]
 [5 6]]


In [6]:
#11)Create 1D and 2D array concatinate those arrays vertically and horizontally. and delete the element using delete function

import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# Create a 2D array
array_2d = np.array([[6, 7, 8], [9, 10, 11]])
print("\n2D Array:")
print(array_2d)

1D Array:
[1 2 3 4 5]

2D Array:
[[ 6  7  8]
 [ 9 10 11]]
